import { Howl } from "howler";
import { AUDIO } from "./constants";
import type { Ambience } from "./constants";

/**
 * Wraps Howler playback for the journey's ambient/flight sound layer.
 * Everything starts muted; nothing plays until the user explicitly enables
 * sound. All source files are synthesized placeholders generated by
 * scripts/generate_audio.py — not recordings of real sound effects.
 *
 * Environment beds are tied to the journey's ambience (sky vs city) and the
 * wing flutter / whoosh gusts are tied to smoothed scroll speed, so motion
 * drives intensity. Everything cross-fades; the whole experience works with
 * audio off.
 */
export class AudioController {
  private enabled = false;
  private ready = false;
  private wind: Howl | null = null;
  private ambienceCity: Howl | null = null;
  private whoosh: Howl | null = null;
  private flutter: Howl | null = null;

  private windId: number | null = null;
  private ambienceId: number | null = null;
  private flutterPlaying = false;
  private lastSpeed = 0;
  private lastWhooshAt = 0;
  private lastWindTarget = -1;
  private lastCityTarget = -1;
  private lastFlutterTarget = -1;
  private flightFadeTimer: ReturnType<typeof setTimeout> | null = null;

  init() {
    if (this.ready) return;
    this.ready = true;
    this.wind = new Howl({ src: ["/audio/wind-cloud.wav"], loop: true, volume: 0 });
    this.ambienceCity = new Howl({ src: ["/audio/ambience-city.wav"], loop: true, volume: 0 });
    this.whoosh = new Howl({ src: ["/audio/whoosh-descend.wav"], volume: 0 });
    this.flutter = new Howl({ src: ["/audio/flutter.wav"], loop: true, volume: 0 });
  }

  setEnabled(enabled: boolean) {
    this.enabled = enabled;
    // Invalidate cached fade targets so update() re-applies them either way.
    this.lastWindTarget = -1;
    this.lastCityTarget = -1;
    this.lastFlutterTarget = -1;
    if (!enabled) {
      this.wind?.fade(this.wind.volume(), 0, 400);
      this.ambienceCity?.fade(this.ambienceCity.volume(), 0, 400);
      this.flutter?.fade(this.flutter.volume(), 0, 400);
      return;
    }
    this.init();
    if (this.windId === null) this.windId = this.wind!.play();
    if (this.ambienceId === null) this.ambienceId = this.ambienceCity!.play();
  }

  get isEnabled() {
    return this.enabled;
  }

  onVisibilityChange(hidden: boolean) {
    if (hidden) {
      this.wind?.pause();
      this.ambienceCity?.pause();
      this.flutter?.pause();
    } else if (this.enabled) {
      this.wind?.play(this.windId ?? undefined);
      this.ambienceCity?.play(this.ambienceId ?? undefined);
      if (this.flutterPlaying) this.flutter?.play();
    }
  }

  /** Call on every journey progress update with the active ambience and smoothed scroll speed (0..1). */
  update(ambience: Ambience, speed: number) {
    if (!this.enabled || !this.ready) return;

    const windTarget = ambience === "sky" ? AUDIO.wind.volume * Math.min(1, 0.4 + speed) : 0;
    const cityTarget = ambience === "city" ? AUDIO.ambience.volume : 0;

    // Only (re)start a fade when the target moves meaningfully — otherwise a
    // stationary scrub would restart every fade ~60×/sec and none would finish.
    if (this.wind && Math.abs(windTarget - this.lastWindTarget) > 0.01) {
      this.wind.fade(this.wind.volume(), windTarget, AUDIO.wind.fadeMs);
      this.lastWindTarget = windTarget;
    }
    if (this.ambienceCity && Math.abs(cityTarget - this.lastCityTarget) > 0.01) {
      this.ambienceCity.fade(this.ambienceCity.volume(), cityTarget, AUDIO.ambience.fadeMs);
      this.lastCityTarget = cityTarget;
    }

    const flutterTarget = speed > 0.08 ? AUDIO.flutter.volume * Math.min(1, speed * 1.5) : 0;
    if (this.flutter && Math.abs(flutterTarget - this.lastFlutterTarget) > 0.01) {
      if (flutterTarget > 0 && !this.flutter.playing()) {
        this.flutter.play();
        this.flutterPlaying = true;
      }
      this.flutter.fade(this.flutter.volume(), flutterTarget, 250);
      this.lastFlutterTarget = flutterTarget;
      if (this.flightFadeTimer) clearTimeout(this.flightFadeTimer);
      if (flutterTarget === 0) {
        this.flightFadeTimer = setTimeout(() => {
          if (this.flutter && this.flutter.volume() < 0.01) {
            this.flutter.pause();
            this.flutterPlaying = false;
          }
        }, AUDIO.flightFadeOutMs);
      }
    }

    // A discreet whoosh "gust" when scroll speed spikes from calm, debounced
    // so fast scrolling doesn't retrigger it repeatedly.
    const now = typeof performance !== "undefined" ? performance.now() : 0;
    if (this.whoosh && speed > 0.55 && this.lastSpeed < 0.3 && now - this.lastWhooshAt > 900) {
      this.whoosh.volume(AUDIO.whoosh.volume);
      this.whoosh.play();
      this.lastWhooshAt = now;
    }
    this.lastSpeed = speed;
  }

  dispose() {
    if (this.flightFadeTimer) clearTimeout(this.flightFadeTimer);
    this.wind?.unload();
    this.ambienceCity?.unload();
    this.whoosh?.unload();
    this.flutter?.unload();
  }
}
